### ISSUE TITLE
unable to get the service working

### ISSUE THREAD

**Issue by kamal2222ahmed** [mannyhuerta/scrumblr#3]
I followed the steps on my Mac, but got:

$node server.js --port 90
Server running at http://127.0.0.1:90/
Please build the React UI using yarn run build:ui or npm run build:ui
now when i try to access http://127.0.0.1:90/ i get:
This site can’t be reached 127.0.0.1 refused to connect.

**Comment by mannyhuerta** [comment]
make sure to build the UI before starting, try npm run build:ui

**Comment by mannyhuerta** [comment]
@kamal2222ahmed I've updated master to be easier to get started - make sure you run npm build:ui before running node server.js
